/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proiect.GUI;

import proiect.Extra.ApiClient;

import javax.swing.*;
import java.awt.*;


public class AdminCRUD_startPage extends javax.swing.JDialog {
    private static ApiClient apiClient;

    /**
     * Creates new form AdminCRUD_startPage
     */
    public AdminCRUD_startPage(Frame parent, ApiClient apiClient) {
        super(parent, false);
        AdminCRUD_startPage.apiClient = apiClient;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JButton manageUsers = new JButton();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        JButton jButton2 = new JButton();
        JButton manageBookings = new JButton();
        JLabel jLabel1 = new JLabel();
        JButton jButton4 = new JButton();
        JButton jButton5 = new JButton();
        JButton jButton6 = new JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        manageUsers.setText("Manage users");

        jButton2.setText("Manage flights");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        manageBookings.setText("Manage bookings");

        jLabel1.setText("Welcome Administrator");

        jButton4.setText("Manage airports");

        jButton5.setText("Manage ratings");

        jButton5.setVisible(false); // TODO intr-o alta versiune xD
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton6.setText("Log out");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(manageUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageBookings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(280, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addComponent(manageUsers)
                .addGap(18, 18, 18)
                .addComponent(manageBookings)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(39, 39, 39))
        );

        manageUsers.addActionListener(e -> {
            Admin_UserManagementUI admin_userManagementUI = new Admin_UserManagementUI((Frame) this.getParent(), true);
            admin_userManagementUI.setLocationRelativeTo(null);
            admin_userManagementUI.setVisible(true);
        });
        manageBookings.addActionListener(e -> {
            BookingsManagement_Admin bookingManagementAdmin = new BookingsManagement_Admin((Frame) this.getParent(), true, apiClient);
            bookingManagementAdmin.setLocationRelativeTo(null);
            bookingManagementAdmin.setVisible(true);
        });

        jButton4.addActionListener(e -> {
            setVisible(false);  // Hide the AdminCRUD_startPage form
            showAirportManagementForm();  // Show the AirportManagement_AdminCRUD form
            setVisible(true);  // Show the AdminCRUD_startPage form when the AirportManagement_AdminCRUD form is closed
        });


        jButton6.addActionListener(evt -> {
            dispose(); // Close the current form

            // Start the LoginUserUI form
            java.awt.EventQueue.invokeLater(() -> {
                LoginUserUI loginUI = new LoginUserUI((Frame) getParent(), true);
                loginUI.setLocationRelativeTo(null);
                loginUI.setVisible(true);
            });
        });

        jButton2.addActionListener(evt -> {
            // Start the new form
            java.awt.EventQueue.invokeLater(() -> {
                // Create a new JFrame
                JFrame frame = new JFrame("Admin CRUD");

                FlightManagement_AdminCRUD flightManagement_adminCRUD = new FlightManagement_AdminCRUD();

                // Create a custom JDialog that extends JDialog and overrides the dispose method
                JDialog flightManagementDialog = new JDialog(frame, "Flight Management", true) {
                    @Override
                    public void dispose() {
                        // Call the dispose method of the JDialog
                        super.dispose();

                        // Show the parent frame again
                        frame.setVisible(true);
                    }
                };

                // Hide the parent frame
                frame.setVisible(false);

                // Add the panel to the custom JDialog
                flightManagementDialog.setContentPane(flightManagement_adminCRUD);
                // Set the size of the JDialog
                flightManagementDialog.setSize(600, 685); // You can adjust this size
                // Center the JDialog
                flightManagementDialog.setLocationRelativeTo(null);
                // Make the JDialog visible
                flightManagementDialog.setVisible(true);
            });
        });



        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void showAirportManagementForm() {
        AirportManagement_AdminCRUD airportManagementForm = new AirportManagement_AdminCRUD();
        JDialog dialog = new JDialog(this, "Airport Management");
        dialog.getContentPane().add(airportManagementForm);
        dialog.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dialog.pack();
        dialog.setModal(true);  // Set the dialog as modal to block execution until it is closed
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminCRUD_startPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            AdminCRUD_startPage dialog = new AdminCRUD_startPage(new JFrame(), apiClient);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // End of variables declaration//GEN-END:variables
}
