/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proiect.GUI;

import proiect.DatabaseTables.Users;
import proiect.Extra.ApiClient;

import javax.swing.*;
import java.io.IOException;


public class LoginUserUI extends javax.swing.JDialog {
    public static String loggedInUserId;
    public static String username;
    private final ApiClient apiClient;
    /**
     * Creates new form UserManagementUI
     */
    public LoginUserUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.apiClient = new ApiClient("http://localhost:8080");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel welcomeLabel = new JLabel();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        JButton buttonLogin = new JButton();
        usernameField = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        JLabel jLabel1 = new JLabel();
        JLabel jLabel2 = new JLabel();
        JLabel jLabel3 = new JLabel();
        JButton jButton1 = new JButton();
        JButton adminButton = new JButton();
adminButton.setVisible(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("Welcome!");

        buttonLogin.setText("Login");

        usernameField.addActionListener(this::usernameFieldActionPerformed);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter your password here:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter your email here:");

        jLabel3.setText("Need an account?");

        jButton1.setText("Register here");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        adminButton.setText("Admin stuff");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(378, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usernameField)
                            .addComponent(jPasswordField1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(386, 386, 386))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(adminButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(welcomeLabel)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(buttonLogin)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(adminButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(39, 39, 39))
        );

        buttonLogin.addActionListener(e -> {
            String email = usernameField.getText();
            String password = new String(jPasswordField1.getPassword());

            try {
                Users user = apiClient.authenticateUser(email, password);
                if (user != null) {
                    loggedInUserId = String.valueOf(user.getId());
                    username=user.getFirstName()+" "+user.getLastName();
                    usernameField.setText("");
                    jPasswordField1.setText("");
                    if ("admin".equals(user.getRole())) {
                        // Open the admin page
                        AdminCRUD_startPage adminCRUD_startPage = new AdminCRUD_startPage((java.awt.Frame) this.getParent(), apiClient);
                        adminCRUD_startPage.setLocationRelativeTo(null);
                        adminCRUD_startPage.addWindowListener(new java.awt.event.WindowAdapter() {
                            @Override
                            public void windowClosing(java.awt.event.WindowEvent e) {
                                // Dispose of the dialog instead of calling dispose() on the parent window
                                adminCRUD_startPage.dispose();
                                LoginUserUI.this.setVisible(true); // Show the original LoginUI
                            }
                        });
                        this.setVisible(false); // Hide the original LoginUI
                        adminCRUD_startPage.setVisible(true);
                    } else if ("user".equals(user.getRole())) {
                        // Open the user management page
                        UserCRUD_startPage userCRUD_startPage = new UserCRUD_startPage((java.awt.Frame) this.getParent());
                        userCRUD_startPage.setLocationRelativeTo(null);
                        userCRUD_startPage.setUserId(); // Set the user ID
                        userCRUD_startPage.addWindowListener(new java.awt.event.WindowAdapter() {
                            @Override
                            public void windowClosing(java.awt.event.WindowEvent e) {
                                userCRUD_startPage.dispose();
                                LoginUserUI.this.setVisible(true); // Show the original LoginUI
                            }
                        });
                        this.setVisible(false); // Hide the original LoginUI
                        userCRUD_startPage.setVisible(true);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid email or password");
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error communicating with the server");
            }
        });

        jButton1.addActionListener(e -> {
            RegisterUserUI registerUserUI = new RegisterUserUI((java.awt.Frame) this.getParent(), true, apiClient);
            registerUserUI.setLocationRelativeTo(null);
            registerUserUI.setVisible(true);
        });
        adminButton.addActionListener(e -> {
            AdminCRUD_startPage AdminCRUD_startPage = new AdminCRUD_startPage((java.awt.Frame) this.getParent(), apiClient);
            AdminCRUD_startPage.setLocationRelativeTo(null);
            AdminCRUD_startPage.setVisible(true);
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed




    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            LoginUserUI dialog = new LoginUserUI(new JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
