/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proiect.GUI;

import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.LocalTime;

import static proiect.GUI.LoginUserUI.username;


public class UserCRUD_startPage extends javax.swing.JDialog {

    /**
     * Creates new form UserCRUD_startPage
     */
    public UserCRUD_startPage(java.awt.Frame parent) {
        super(parent, false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JButton manageUsers = new JButton();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        JButton jButton3 = new JButton();
        JButton jButton5 = new JButton();
        JButton jButton6 = new JButton();
        JLabel jLabel1 = new JLabel();
        JLabel userNameLabel = new JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        manageUsers.setText("Manage my account");

        jButton3.setText("Manage my bookings");

        jButton5.setText("Manage my ratings");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton6.setText("Log out");
        jButton5.setVisible(false);//TODO ratings in alta versiune



        LocalTime currentTime = LocalTime.now();
        if (currentTime.isAfter(LocalTime.of(18, 0)) || currentTime.isBefore(LocalTime.of(6, 0))) {
            jLabel1.setText("Good evening, ");
        } else {
            jLabel1.setText("Good day, ");
        }

        userNameLabel.setText(username);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userNameLabel))
                .addGap(98, 98, 98)
                .addComponent(manageUsers)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(16, 16, 16))
        );
        manageUsers.addActionListener(e -> {
            UserCRUD_startPage.this.setVisible(false);
            UserManagementUI userManagementUI = new UserManagementUI((Frame) this.getParent(), true);
            userManagementUI.setLocationRelativeTo(null);

            userManagementUI.addWindowListener(new WindowAdapter() {
                @Override

                public void windowClosing(WindowEvent e) {
                    UserCRUD_startPage.this.setVisible(true);
                }
            });

            userManagementUI.setVisible(true);
        });

        jButton3.addActionListener(e -> {
            // Close the UserCRUD_startPage dialog
            UserCRUD_startPage.this.setVisible(false);

            // Create a new BookingManagement_UserUI frame with the logged-in user's ID
            BookingManagement_UserUI bookingUI = new BookingManagement_UserUI(Long.valueOf(LoginUserUI.loggedInUserId));

            // Add a WindowListener to the BookingManagement_UserUI window
            bookingUI.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    // Reopen the UserCRUD_startPage dialog when the window is closing
                    UserCRUD_startPage.this.setVisible(true);
                }
            });
        });
        jButton6.addActionListener(evt -> {
            dispose(); // Close the current form

            // Start the LoginUserUI form
            EventQueue.invokeLater(() -> {
                LoginUserUI loginUI = new LoginUserUI((Frame) getParent(), true);
                loginUI.setLocationRelativeTo(null);
                loginUI.setVisible(true);
            });
        });
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserCRUD_startPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            UserCRUD_startPage dialog = new UserCRUD_startPage(new JFrame());
            dialog.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    public void setUserId() {
    }
    // End of variables declaration//GEN-END:variables
}
